os: linux
dist: xenial
arch: amd64

before_install:
  - sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

language: node_js
node_js:
  - v14.15.0

script: yarn coveralls
