export const jobs = [
  ['alchemist', 'alchimiste', 'alchi'],
  ['jeweller', 'bijoutier', 'bijou'],
  ['handyman', 'bricoleur', 'brico'],
  ['lumberjack', 'bûcheron', 'bucheron', 'buch'],
  ['hunter', 'chasseur'],
  ['shoemagus', 'cordomage'],
  ['shoemaker', 'cordonnier', 'cordo'],
  ['costumagus', 'costumage', 'costu'],
  ['craftmagus', 'façomage', 'facomage'],
  ['artificer', 'façonneur', 'faconneur'],
  ['smithmagus', 'forgemage'],
  ['smith', 'forgeron'],
  ['jewelmagus', 'joaillomage', 'joaillo'],
  ['miner', 'mineur'],
  ['farmer', 'paysan'],
  ['fisherman', 'pêcheur', 'pecheur'],
  ['carvmagus', 'sculptemage'],
  ['carver', 'sculpteur'],
  ['tailor', 'tailleur']
];
